//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCNET.UI.Models.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyLog
    {
        public int LogID { get; set; }
        public string LogAciklama { get; set; }
        public string LogTipi { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
