//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCNET.UI.Models.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public System.Guid OgrenciID { get; set; }
        public string OgrenciAdi { get; set; }
    }
}
